### ISSUE TITLE
helm chart missing for poeple not using gclood

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x-labs/helmboot#19]
I think that before terraform, we should just have a simple helm file with all the required resources (serviceaccounts...) for everybody to be able to use jxl boot run

**Comment by jstrachan** [comment]
agreed. I've started a script for `kind` here: https://github.com/jenkins-x-labs/cloud-resources/tree/master/kind

in general all the k8s resources should be in the helm charts; the only need for additional scripts is to setup the cluster and any other cloud infrastructure thats not a k8s resource

**Comment by yelhouti** [comment]
Fixed by another commit If I remember correctly, closing
